/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_reziena_user_reziena_1_MainActivity_Task */

#ifndef _Included_com_reziena_user_reziena_1_MainActivity_Task
#define _Included_com_reziena_user_reziena_1_MainActivity_Task
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
