/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_reziena_user_reziena_1_MainActivity */

#ifndef _Included_com_reziena_user_reziena_1_MainActivity
#define _Included_com_reziena_user_reziena_1_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_reziena_user_reziena_1_MainActivity_PERMISSIONS_REQUEST_CODE
#define com_reziena_user_reziena_1_MainActivity_PERMISSIONS_REQUEST_CODE 100L
/*
 * Class:     com_reziena_user_reziena_1_MainActivity
 * Method:    Detect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_reziena_user_reziena_11_MainActivity_Detect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
